### PR TITLE
Stylus setup for aurora subtheme

### PR DESCRIPTION
**Pull request by gregfedorov**
Initial, very early, but working Stylus based aurora sub-theme. (using stylus eliminates multiple dependencies in the project and only leaves node.js as the one true dependency for everything)

### CODE REVIEW

**Comment by iamcarrico** [comment]
I am hesitant to allow this for a few reasons:

* Generally, the Drupal community has gotten behind Sass, and all of the major base themes represented within here use Sass exclusively. 
* This does not add in support for stylus as much as just remove the specific Sass files
* This does extra things past that (e.g. add in the panels layout settings within the info file) that are not related to stylus. 
* As far as dependencies go, this weekend #24 was already opened to give LibSass support— which will remove the ruby dependency. 
* I have no experience with Stylus, and have no intention of supporting Stylus coding in the future.

**Comment by gregfedorov** [comment]
Hello!
All good points, but just as clarification:
Stylus support is implicit with the included package.json and gulpfile.js (this forces gulp). 

This is my first experience with yeoman generators, so it is a bit "clumsy". I'll probably end up spinning up a dedicated generator just for this, though I am a huge fan of Aurora. 

SASS appears a clear winner at the moment, but do keep an eye on Stylus! It's got all the qualities of an underdog waiting in the wings.

Thanks for the feedback!

**Comment by gregfedorov** [comment]
Well, this is embarrassing, I just realised most of the changes did not make it to the pull request. I needs more coffee! Just for posterity's sake submitting a new one.

**Comment by iamcarrico** [comment]
Add it to this branch so the conversation can continue in a single location.

**Pull request closed without merging**
