### PR TITLE
switched from execSync to sync-exec node modules

### PR DESCRIPTION
**Pull request by eft**
[execSync](https://github.com/mgutz/execSync) no longer works on node.js 0.12 and is no longer maintained.  This pull request replaces execSync with [exec-sync](https://github.com/gvarsanyi/sync-exec).  [Note : Node.js 0.12 also includes child_process.execSync, which may eventually be a cleaner solution.]

This request also changes the casing on two of the exec/templates files, which were throwing errors.

```
/var/foo/.nvm/versions/node/v0.12.0/lib/node_modules/generator-drupal-theme/node_modules/yeoman-generator/lib/actions/actions.js:194
    throw new Error('Unable to read "' + filepath + '" file (Error code: ' + e
          ^
Error: Unable to read "/var/foo/.nvm/versions/node/v0.12.0/lib/node_modules/generator-drupal-theme/extras/templates/gulpfile.js" file (Error code: ENOENT).
```

### CODE REVIEW

**Comment by Cottser** [comment]
The execSync -> sync-exec stuff works as expected and code looks good. Thanks @eft! +1 from me.

As far as the template case changes, I think only gulpfile should be lowercased: https://github.com/frontend-united/generator-drupal-theme/blob/5796f35dce1d73ad0bb4cec2f89d3f31c68ceed0/extras/index.js#L97

I would suggest that it might make sense to move that change to a separate PR because it does seem to be a separate issue.

**Comment by mikl** [comment]
Happy to report that this fix also works for io.js :)

**Comment by iamcarrico** [comment]
Awesome. I will commit this next week. (SXSW is keeping me busy now)

On Wednesday, March 18, 2015, Mikkel Høgh <notifications@github.com> wrote:

> Happy to report that this fix also works for io.js :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frontend-united/generator-drupal-theme/pull/19#issuecomment-83255975>
> .
>


-- 

Ian J. Carrico

Making the web better, 1ms at a time.
Ian@iancarrico.com
(+1) 512.827.7502
iamcarrico.com
@iamcarrico <http://www.twitter.com/iamcarrico>

**Comment by theodorosploumis** [comment]
This fix is not committed to any **git tag**. It is only on master. This way if someone installs the npm with the command 

`npm install generator-drupal-theme` 

he/she will get latest tag of 0.1.6 which does not have the fix.

Here is the open issue with the exact same problem https://github.com/frontend-united/generator-drupal-theme/issues/20

**Pull request merged**
